### ISSUE TITLE
Clean install of version 0.75

### ISSUE THREAD

**Issue by epigraphe** [H2-invent/jitsi-admin#355]
Good day.
What steps should I take to install version 0.75.8 on a clean server?
Do I understand correctly that I need to download the archive with the release, then install the websocket according to the instructions, and then run bash install.sh?

**Comment by supczinskib** [comment]
> Good day.
> What steps should I take to install version 0.75.8 on a clean server?
> Do I understand correctly that I need to download the archive with the release, then install the websocket according to the instructions, and then run bash install.sh?

It is possible, but it will be a difficult task. There is no comprehensive installation guide, and the "install.sh" script does not contain all the required steps.

**Comment by holema** [comment]
Hello, do you want to install the Jitsi-Admin in a docker environment? I would recoomend to install in the docker setup.

**Comment by epigraphe** [comment]
I think I did everything.
I have installed keycloak 20.0.0.3, apache with modrewrite, php 8.1 and websocket. 
I can login to keycloak, created a realm, a client and a secret there. 
I was able to open jitsy-admin main page, but when I click on the login button, I get a 404 with a gopher and a strange address in the line

The start looks like this:
https://cp.xxx.yyy/keycloak.xxx.yyy/realms/jitsi-admin/protocol/openid-connect/auth?scope=ema...

And I can't start websocket, I get the following error:

systemd[1264]: jitsi-admin-websocket.service: Failed to set up standard output: No such file or directory
systemd[1264]: jitsi-admin-websocket.service: Failed at step STDOUT spawning /usr/bin/node: No such file or directory
systemd[1]: jitsi-admin-websocket.service: Main process exited, code=exited, status=209/STDOUT
systemd[1]: jitsi-admin-websocket.service: Failed with result 'exit-code'.

In ENV.LOCAL I have the following value - 

###<WEBSOCKET CREDENTIALS
WEBSOCKET_SECRET=<WEBSOCKET_SECRET>

<WEBSOCKET_SECRET> - This is what I put in the websocket setup as a secret, because I don't have anything about mercury

What could be my mistake?

**Comment by holema** [comment]
So you set up the KEAYCLOAK Enviroment Variables? 
```
###> hwi/oauth-bundle ###
OAUTH_KEYCLOAK_CLIENT_ID=addHere
OAUTH_KEYCLOAK_CLIENT_SECRET=addHere
OAUTH_KEYCLOAK_SERVER=addHere/auth
OAUTH_KEYCLOAK_REALM=addHere
###< hwi/oauth-bundle ###
```
For Version 20 you should remove the /auth behind the URL. So it is only the URL of the Keycloak-Server. Keycloak changed here a lot on KC20

For the Websocket:
There was a step missing : `npm install`.

I fixed the instruction and it worked in my envoironment.
https://github.com/H2-invent/jitsi-admin/wiki/Websocket-installation

**Comment by epigraphe** [comment]
Thank you very much for your continued help in this matter.

`KEAYCLOAK Enviroment Variables`
This block is filled during the installation script, I have data in it.
/auth is not in this block, FQDN only

Thanks for the edits about the websocket, I did everything and got the active (running) status

But, unfortunately, the first problem persisted(

I see the main jitsi-admin page, hover over the login button and see the address https://cp.xxx.yyy/room/dashboard

But when i click on it, the url becomes https://cp.xxx.yyy/keycloak.xxx.yyy/realms/jitsi-admin/protocol/openid-connect/auth?sco........ ..... and I get a 404 error

cp.xxx.yyy is the jitsi-admin address, keycloak.xxx.yyy is the keycloak address

If I remove the jitsi address (сp.xxx.yyy) from this url and try to open a link starting with keycloak (keycloak.xxx.yyy/realms/jitsi-admin/protocol/openid-connect/auth?sco........), I get 

"We are sorry...
Invalid parameter: redirect_uri"

**Comment by holema** [comment]
Hello @epigraphe,

Great the websocket is now working. THanks for your help to improve the instruction We need this feedback.
The second problem. In the .env.local file there must be a entry called `OAUTH_KEYCLOAK_SERVER=addHere/auth`
Here should be the keycloak server url (https://your-keycloak.org) without the /auth at the ending. Can you check this for me. I think here is the jitsi-admin url somewhere included. Propably you forget to dd the https:// in the installation script. because then the cp.xxx.yyy is put infront of it.

Have you setup the redirect uri in the Keycloak? there is in the client tab a redirect field. There you have to set https://cp.xxx.yyy* to wildcard all URLs from the jitsi-admin.

I hope this will work.

**Comment by epigraphe** [comment]
This is what my block looks like:

```
###> hwi/oauth-bundle ###
OAUTH_KEYCLOAK_CLIENT_ID=jitsi_admin
OAUTH_KEYCLOAK_CLIENT_SECRET=dnDsrPP7ZS5kNjAY5XXXXXXXXXXX
OAUTH_KEYCLOAK_SERVER=https://keycloak.xxx.yyy
OAUTH_KEYCLOAK_REALM=jitsi-admin
###< hwi/oauth-bundle ###
```
Initially, the server would have been specified without HTTPS, I added HTTPS and rebooted the entire server. Nothing changed and, Unfortunately, I keep getting 404 errors.

I get it even if I manually write the path like https in the address bar

![image](https://user-images.githubusercontent.com/6083395/213639301-16b0b2cf-aee8-47be-8668-9b006dfb6033.png)



In keycloak, I wrote in the settings what you wrote. The behavior has changed: now when I open a keycloak direct address, it asks me for a username and password. After entering and pressing the sign in, the button turns gray and nothing happens.

![image](https://user-images.githubusercontent.com/6083395/213639373-dfb6993d-d20d-46e6-a480-9cda1f25ec8a.png)

If after that I try again - I get an error 500

**Comment by holema** [comment]
Hello @epigraphe,

It is very strange, that in the keycloak URL you have both domeins. first the jitsi-admin domain is set and then the KC domain.

HEre we have to take a look from where this can come, because in our testcase this never happens.

The second problem seems to be a firewall issue. Is the jitsi-admin allowed to talk to the KC Server? and is the KC Server with an Lets-Encrypt Certificate or a selfsigned Certificate.

You can write me a email to entwicklung@h2-invent.com so we can have a small look on you problem.

**Comment by holema** [comment]
closed because of inactivity
